"""Pre-populated submission guidelines for top journals in economics and political science."""

JOURNAL_PRESETS: list[dict] = [
    # ── Economics ──────────────────────────────────────────────
    {
        "id": "aer",
        "name": "American Economic Review",
        "abbreviation": "AER",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/aer/submissions/accepted-articles/styleguide",
        "rules": {
            "journal_name": "American Economic Review",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required.",
                "Online appendices accepted for supplementary material.",
            ],
        },
    },
    {
        "id": "econometrica",
        "name": "Econometrica",
        "abbreviation": "ECMA",
        "field": "economics",
        "guidelines_url": "https://www.econometricsociety.org/publications/econometrica/information-authors",
        "rules": {
            "journal_name": "Econometrica",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Econometrica house style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts must be submitted as PDF.",
                "Supplementary material should be in a separate appendix.",
            ],
        },
    },
    {
        "id": "qje",
        "name": "Quarterly Journal of Economics",
        "abbreviation": "QJE",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/qje/pages/submission-guidelines",
        "rules": {
            "journal_name": "Quarterly Journal of Economics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Author-date (Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "All submissions must be blinded.",
                "Data and code must be made available upon acceptance.",
            ],
        },
    },
    {
        "id": "jpe",
        "name": "Journal of Political Economy",
        "abbreviation": "JPE",
        "field": "economics",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jpe/instruct",
        "rules": {
            "journal_name": "Journal of Political Economy",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Chicago Manual of Style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express.",
                "Replication data required upon acceptance.",
            ],
        },
    },
    {
        "id": "restud",
        "name": "Review of Economic Studies",
        "abbreviation": "ReStud",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/restud/pages/General_Instructions",
        "rules": {
            "journal_name": "Review of Economic Studies",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts should not exceed 50 pages including appendices.",
                "Data availability policy applies upon acceptance.",
            ],
        },
    },
    {
        "id": "aej-applied",
        "name": "AEJ: Applied Economics",
        "abbreviation": "AEJ:Applied",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/app/submissions/accepted-articles/styleguide",
        "rules": {
            "journal_name": "American Economic Journal: Applied Economics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required.",
                "Follow AEA data availability policy.",
            ],
        },
    },
    {
        "id": "aej-macro",
        "name": "AEJ: Macroeconomics",
        "abbreviation": "AEJ:Macro",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/mac/submissions/accepted-articles/styleguide",
        "rules": {
            "journal_name": "American Economic Journal: Macroeconomics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required.",
                "Follow AEA data availability policy.",
            ],
        },
    },
    {
        "id": "jof",
        "name": "Journal of Finance",
        "abbreviation": "JF",
        "field": "economics",
        "guidelines_url": "https://afajof.org/journal-of-finance/submission-guidelines/",
        "rules": {
            "journal_name": "Journal of Finance",
            "word_limit": None,
            "page_limit": 60,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Journal of Finance house style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts must be double-spaced with 1-inch margins.",
                "All submissions must be anonymous.",
            ],
        },
    },
    {
        "id": "restat",
        "name": "Review of Economics and Statistics",
        "abbreviation": "ReStat",
        "field": "economics",
        "guidelines_url": "https://direct.mit.edu/rest/pages/submission-guidelines",
        "rules": {
            "journal_name": "Review of Economics and Statistics",
            "word_limit": None,
            "page_limit": 40,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Shorter papers are preferred.",
                "Replication data required.",
            ],
        },
    },
    {
        "id": "jeea",
        "name": "Journal of the European Economic Association",
        "abbreviation": "JEEA",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/jeea/pages/General_Instructions",
        "rules": {
            "journal_name": "Journal of the European Economic Association",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Submissions must be blinded for review.",
                "Data availability statement required upon acceptance.",
            ],
        },
    },
    # ── Political Science ─────────────────────────────────────
    {
        "id": "apsr",
        "name": "American Political Science Review",
        "abbreviation": "APSR",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/american-political-science-review/information/instructions-contributors",
        "rules": {
            "journal_name": "American Political Science Review",
            "word_limit": 12000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Word limit of 12,000 words including footnotes.",
                "Manuscripts must be fully anonymized.",
                "Replication materials must be provided upon acceptance.",
            ],
        },
    },
    {
        "id": "ajps",
        "name": "American Journal of Political Science",
        "abbreviation": "AJPS",
        "field": "political_science",
        "guidelines_url": "https://ajps.org/guidelines-for-manuscripts/",
        "rules": {
            "journal_name": "American Journal of Political Science",
            "word_limit": 10000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Word limit of 10,000 words including notes, references, tables, and figures.",
                "Verification policy: replication materials required.",
            ],
        },
    },
    {
        "id": "jop",
        "name": "Journal of Politics",
        "abbreviation": "JOP",
        "field": "political_science",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jop/instruct",
        "rules": {
            "journal_name": "Journal of Politics",
            "word_limit": 10000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts should not exceed 35 pages double-spaced.",
                "Replication data required upon acceptance.",
            ],
        },
    },
    {
        "id": "bjps",
        "name": "British Journal of Political Science",
        "abbreviation": "BJPS",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/british-journal-of-political-science/information/instructions-contributors",
        "rules": {
            "journal_name": "British Journal of Political Science",
            "word_limit": 12000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Harvard",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Harvard style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "12,000 word limit including footnotes and references.",
                "British spelling preferred.",
            ],
        },
    },
    {
        "id": "cps",
        "name": "Comparative Political Studies",
        "abbreviation": "CPS",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/CPS",
        "rules": {
            "journal_name": "Comparative Political Studies",
            "word_limit": 12000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts should not exceed 12,000 words including references.",
                "Include a 150-word abstract and 4-5 keywords.",
            ],
        },
    },
    {
        "id": "world-politics",
        "name": "World Politics",
        "abbreviation": "WP",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/world-politics/information/instructions-contributors",
        "rules": {
            "journal_name": "World Politics",
            "word_limit": 15000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Chicago Manual of Style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Research articles typically 10,000-15,000 words.",
                "Footnotes rather than endnotes.",
            ],
        },
    },
    {
        "id": "io",
        "name": "International Organization",
        "abbreviation": "IO",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/international-organization/information/instructions-contributors",
        "rules": {
            "journal_name": "International Organization",
            "word_limit": 15000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Chicago Manual of Style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts should not exceed 15,000 words.",
                "Include an abstract of no more than 150 words.",
            ],
        },
    },
    {
        "id": "political-analysis",
        "name": "Political Analysis",
        "abbreviation": "PA",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/political-analysis/information/instructions-contributors",
        "rules": {
            "journal_name": "Political Analysis",
            "word_limit": 10000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 200,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Replication materials required.",
                "Software and data must be deposited in the Political Analysis Dataverse.",
            ],
        },
    },
    {
        "id": "arps",
        "name": "Annual Review of Political Science",
        "abbreviation": "ARPS",
        "field": "political_science",
        "guidelines_url": "https://www.annualreviews.org/page/authors/author-instructions/preparing/review-articles",
        "rules": {
            "journal_name": "Annual Review of Political Science",
            "word_limit": 15000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": ["Abstract", "Introduction", "Conclusion"],
            "abstract_word_limit": 200,
            "citation_style": "Numbered",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "Annual Reviews numbered citation style",
            "anonymization_required": False,
            "additional_notes": [
                "Invited review articles only.",
                "Manuscripts should be approximately 12,000-15,000 words.",
            ],
        },
    },
    {
        "id": "jcr",
        "name": "Journal of Conflict Resolution",
        "abbreviation": "JCR",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/JCR",
        "rules": {
            "journal_name": "Journal of Conflict Resolution",
            "word_limit": 12000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APSA",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Manuscripts should not exceed 12,000 words.",
                "Include a structured abstract and 4-5 keywords.",
            ],
        },
    },
]


def get_presets_list() -> list[dict]:
    """Return a lightweight list of presets for the frontend dropdown."""
    return [
        {
            "id": p["id"],
            "name": p["name"],
            "abbreviation": p["abbreviation"],
            "field": p["field"],
        }
        for p in JOURNAL_PRESETS
    ]


def get_preset_rules(preset_id: str) -> dict | None:
    """Return the full rules dict for a given preset ID."""
    for p in JOURNAL_PRESETS:
        if p["id"] == preset_id:
            return p["rules"]
    return None
