"""Pre-populated submission guidelines for top journals in economics and political science."""

JOURNAL_PRESETS: list[dict] = [
    # ── Economics ──────────────────────────────────────────────
    {
        "id": "aer",
        "name": "American Economic Review",
        "abbreviation": "AER",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/aer/submissions",
        "rules": {
            "journal_name": "American Economic Review",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 11.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "figures/tables included in page count; captions below figures, above tables",
            },
            "reference_format": "Chicago Manual Author-Date style",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review (author names visible to referees; referees anonymous to authors). No anonymization required.",
                "Submit via ScholarOne Manuscripts as PDF. AEA LaTeX templates available (use in 'review mode').",
                "Strongly recommended not to exceed 40 pages at 11pt/1.5 spacing, or 45 pages at 12pt/1.5 spacing. Page limit includes figures, tables, references, and appendices.",
                "Title, byline, and author affiliations on the first page (no separate title page).",
                "JEL codes required; entered during ScholarOne submission.",
                "Separate Disclosure Statement PDF required for each co-author at submission. Must disclose financial conflicts and IRB status. Submissions without disclosure are incomplete.",
                "Appendix goes last, after bibliography, using regular section headings.",
                "Supplemental appendix allowed as separate PDF for nonessential extensions. Not edited or typeset by journal.",
                "AEA Data and Code Availability Policy: replication materials archived in AEA Data and Code Repository upon conditional acceptance.",
                "Field experiments must be registered in AEA RCT registry with citation in acknowledgment footnote.",
                "Submission fee adjusted by AEA membership and country income classification. 50% refund for desk rejections.",
                "Publication fee: $15 per typeset page (papers first submitted on/after Feb 1, 2024).",
                "Previously rejected AER papers cannot be resubmitted.",
                "Plagiarism screening via CrossRef Similarity Check.",
            ],
        },
    },
    {
        "id": "econometrica",
        "name": "Econometrica",
        "abbreviation": "ECMA",
        "field": "economics",
        "guidelines_url": "https://www.econometricsociety.org/publications/econometrica/information-authors",
        "rules": {
            "journal_name": "Econometrica",
            "word_limit": 17000,
            "word_count_includes": ["body", "references", "appendix"],
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1.25 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text where they naturally belong (NOT at end of document)",
            },
            "reference_format": "Econometrica house style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express as single PDF.",
                "45-page limit AND 17,000-word limit. No more than 32 lines per page. Includes references and appendices.",
                "At least 12pt font, at least 1.5 spacing, at least 1.25-inch margins.",
                "Title page must include abstract (150 words max), keywords, and full author affiliations. Pages must be numbered.",
                "Footnotes and figures should NOT be placed at end — place where they naturally belong in text.",
                "Supplemental appendix: max 25 pages, same formatting as main text. Must be clearly labeled. Main paper must be self-contained.",
                "Page limit exceptions may be granted; email Editor before submission.",
                "At least one author must be a member of the Econometric Society.",
                "Submission fee: US$125 (regular), US$50 (students). Low-income country residents exempt.",
                "Publication fee: 50% of production cost per page. Low-income/lower-middle-income residents exempt.",
                "Data/replication: raw data, code, and documentation required before acceptance for empirical/simulation/experimental studies.",
                "Working paper version should be publicly available (personal website or public repository).",
                "AI tools may be used but authors remain fully responsible. AI may not be listed as an author.",
                "Random author ordering symbol (r) is NOT allowed. May explain ordering in footnote.",
            ],
        },
    },
    {
        "id": "qje",
        "name": "Quarterly Journal of Economics",
        "abbreviation": "QJE",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/qje/pages/Instructions_To_Authors",
        "rules": {
            "journal_name": "Quarterly Journal of Economics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 250,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "included in single PDF for review; high-res .tif files required upon acceptance",
            },
            "reference_format": "Author-date (Chicago-based). Complete first and last names in references.",
            "anonymization_required": False,
            "additional_notes": [
                "Not double-blind; author names appear under title on first page.",
                "Submit via Editorial Express; save as .doc, .rtf, or TeX. Final submission as single PDF.",
                "Abstract: no more than 250 words. JEL codes at end of abstract.",
                "First page must include: title, contributor names, corresponding author address/email, total word count, abstract, and acknowledgment footnote.",
                "Manuscript order: title page -> text -> author affiliations -> appendix -> references -> notes -> tables -> figures.",
                "All funding sources disclosed in first footnote, denoted by asterisk at end of article title.",
                "When creating PDF, select 'embed all fonts' for mathematical symbols.",
                "Style guide: Chicago Manual of Style for items not covered by QJE-specific style.",
                "Data/replication: papers published only if data clearly documented and available. Replication materials deposited in QJE Dataverse prior to publication.",
                "Cover letter should notify if data are proprietary or replication requirements cannot be met.",
                "Copyright permissions needed for prose extracts >400 words or series totaling >800 words.",
                "No submission fee.",
            ],
        },
    },
    {
        "id": "jpe",
        "name": "Journal of Political Economy",
        "abbreviation": "JPE",
        "field": "economics",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jpe/instruct",
        "rules": {
            "journal_name": "Journal of Political Economy",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "indicate location in margin of text",
            },
            "reference_format": "Chicago Manual of Style (author-date)",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review (author names disclosed to referees).",
                "Submit via Editorial Manager (editorialmanager.com/jpolec); PDF, .doc, or .tex accepted.",
                "Title page must include names, email addresses, and affiliations of all authors.",
                "Supplemental appendix allowed for online posting. All findings must be documented in manuscript or supplement.",
                "Figures: no JPEG (lossy compression unsuitable for print). Sans serif (Arial, Helvetica) preferred for figure labels. All fonts embedded or converted to outlines.",
                "Figures intended for B&W must not contain color objects. Color may incur charges.",
                "Tables: do not break cell contents across cells. Use roman font; italic/bold NOT for emphasis in tables.",
                "LaTeX strongly urged for math-intensive articles.",
                "Data/replication: papers published only if data clearly documented and available. Posted on JPE site.",
                "Submission fee: $250 for non-subscribers; $125 for individual JPE subscribers. Reviewer fee waiver for 3+ reports in prior 12 months. Non-refundable; decisions not released until paid.",
                "Authors of comments must correspond with original author(s) and include correspondence with cover letter.",
            ],
        },
    },
    {
        "id": "restud",
        "name": "Review of Economic Studies",
        "abbreviation": "ReStud",
        "field": "economics",
        "guidelines_url": "https://www.restud.com/submissions/",
        "rules": {
            "journal_name": "Review of Economic Studies",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "included in manuscript",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express as single PDF.",
                "45-page limit including title page, tables, figures, references, and appendices.",
                "12pt font, 1.5 spacing (references/footnotes can be single-spaced), at least 1-inch margins.",
                "Title page: short, specific title. First name, initials, and surname of each author with department, institution, city/postcode, country. Fax, telephone, and email of corresponding author.",
                "Only one corresponding author (editorial policy).",
                "Keywords required. JEL codes required upon submission.",
                "Online appendix: max 30 pages, same formatting requirements. Clearly labeled 'Online Appendix'. Main paper must be self-contained including proofs of key results.",
                "Submission fee: USD $200 (new submissions). Reduced fee USD $120 if each author is a student, within 6 years of PhD, or in low/middle-income economy.",
                "Data/replication: supplementary data files required for publication alongside articles.",
                "ReStud uses a 'reject and resubmit' model (no revise and resubmit).",
            ],
        },
    },
    {
        "id": "aej-applied",
        "name": "AEJ: Applied Economics",
        "abbreviation": "AEJ:Applied",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/app/submissions",
        "rules": {
            "journal_name": "American Economic Journal: Applied Economics",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 11.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "figures/tables included in page count; captions below figures, above tables",
            },
            "reference_format": "Chicago Manual Author-Date style",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review. Same formatting as AER (AEA journals share common formatting).",
                "Submit via ScholarOne as PDF. AEA LaTeX templates available.",
                "Recommended not to exceed 40-45 pages at 11pt/1.5 spacing/1-inch margins.",
                "JEL codes required. Separate Disclosure Statement PDF required for each co-author.",
                "Supplemental appendix allowed as separate PDF. Not edited or typeset by journal.",
                "AEA Data and Code Availability Policy: replication materials archived in AEA Data and Code Repository.",
                "Field experiments must be registered in AEA RCT registry.",
                "Submission fee adjusted by AEA membership and country income. 50% refund for desk rejections.",
                "Accepts transfers from AER/AER: Insights. Previously rejected papers should not be resubmitted.",
            ],
        },
    },
    {
        "id": "aej-macro",
        "name": "AEJ: Macroeconomics",
        "abbreviation": "AEJ:Macro",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/mac/submissions",
        "rules": {
            "journal_name": "American Economic Journal: Macroeconomics",
            "word_limit": None,
            "page_limit": 40,
            "font": "Times New Roman",
            "font_size": 11.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "figures/tables included in page count; captions below figures, above tables",
            },
            "reference_format": "Chicago Manual Author-Date style",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review. Same formatting as AER.",
                "Submit via ScholarOne as PDF. AEA LaTeX templates available.",
                "Strongly recommended not to exceed 40 pages at 11pt/1.5 spacing. Average article is 34-35 typeset pages.",
                "JEL codes required. Separate Disclosure Statement PDF required for each co-author.",
                "Supplemental appendix allowed as separate PDF.",
                "AEA Data and Code Availability Policy: replication materials archived in AEA Data and Code Repository.",
                "Field experiments must be registered in AEA RCT registry.",
                "Submission fee adjusted by AEA membership and country income. 50% refund for desk rejections.",
                "Publication fee: $15 per typeset page (papers first submitted on/after Feb 1, 2024).",
                "Accepts transfers from AER/AER: Insights.",
            ],
        },
    },
    {
        "id": "jof",
        "name": "Journal of Finance",
        "abbreviation": "JF",
        "field": "economics",
        "guidelines_url": "https://afajof.org/submissions/",
        "rules": {
            "journal_name": "Journal of Finance",
            "word_limit": None,
            "page_limit": 60,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch sides, 1.5 inch top/bottom",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "included in 60-page limit; indicate location in margin of text; color encouraged for online",
            },
            "reference_format": "Journal of Finance house style (author-date, Chicago-based)",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review.",
                "Submit via ScholarOne as PDF only.",
                "60-page maximum strictly enforced — exceeding causes immediate desk rejection. Includes internal appendices, references, figures, and tables.",
                "First page: author names, title, and abstract. At least 1.5 spacing, 12pt minimum.",
                "Disclosure statement REQUIRED on page following title page (not separate file, not in acknowledgments). Each co-author must have separate declaration by name. Must include even if nothing to disclose. ~50% of submissions returned for missing disclosure.",
                "Internet Appendix: placed at END of manuscript PDF (same file, not separate upload). Must have 'Internet Appendix' as title. Does NOT count toward 60-page limit. Paper must be self-contained without it.",
                "Code sharing policy: code for all results must be submitted with final version, posted in Supplementary Information. Exemption requests in cover letter at first submission.",
                "Data editor examines materials for accuracy and replicability.",
                "Submission fee paid by credit card. Reviewing credits can offset fees. $200 flat refund for desk rejections from high-income countries. Full refund if editorial decision >100 days.",
            ],
        },
    },
    {
        "id": "restat",
        "name": "Review of Economics and Statistics",
        "abbreviation": "ReStat",
        "field": "economics",
        "guidelines_url": "https://direct.mit.edu/rest/pages/submission-guidelines",
        "rules": {
            "journal_name": "Review of Economics and Statistics",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "each on separate page with caption; vertical rules omitted; figures in B&W",
            },
            "reference_format": "Author-year in-text (name, year, pages). References: complete first/last names, publication, volume, month, year, pages.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express as PDF.",
                "Accepted papers: 45 pages or less, double-spaced, 12pt, 1-inch margins. Includes text, tables, figures, references, and all print material.",
                "Short papers: strictly 6,000 words and 5 exhibits max. For each exhibit below 5, add up to 200 words. Word count via AEA word count tool required.",
                "JEL codes required (editor assignments determined by JEL codes).",
                "Tables: each on separate page with caption. Vertical rules omitted. Captions/legends must be understandable without text.",
                "Figures: each on separate page with caption. B&W, clean print. Axis dimensions clearly labeled.",
                "Footnotes: numbered consecutively, double-spaced, same font size. Preferably at back of paper. Limit equations in footnotes.",
                "Equations: column width 3 inches — long equations should be designed for easy division.",
                "Abbreviations: all but most common spelled out on first use.",
                "Online appendices allowed with no size restrictions.",
                "Submission fee: nonrefundable; waived if one author has current individual subscription.",
                "Cover letter in PDF format.",
                "Resubmissions by invitation only. Turnaround: >90% within 4 months.",
            ],
        },
    },
    {
        "id": "jeea",
        "name": "Journal of the European Economic Association",
        "abbreviation": "JEEA",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/jeea/pages/Author_Guidelines",
        "rules": {
            "journal_name": "Journal of the European Economic Association",
            "word_limit": None,
            "page_limit": 40,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 1200,
                "max_file_size_mb": None,
                "placement": "figure captions UNDERNEATH; table captions ABOVE (notes below). No halftones; use diagonal lines/crosshatch. No lines thinner than 0.5pt.",
            },
            "reference_format": "Author-date (house style). Times-Roman preferred in figures.",
            "anonymization_required": False,
            "additional_notes": [
                "Single-blind review (author names disclosed to reviewers).",
                "Submit via Editorial Express as PDF only.",
                "40 pages with 1.5 spacing (or 50 pages double-spaced). Font, margin, and spacing requirements also apply to references and tables.",
                "Front page must show title and authors. Format of affiliations, email, abstract, and acknowledgments is flexible.",
                "Submitting author must be a member of the European Economic Association.",
                "Use double quotes (not single). Do not italicize Latin expressions (e.g., 'et al.' not italic).",
                "Appendix labeling: all elements labeled A, B, etc. Supplementary material must be referred to in main manuscript.",
                "Alt text required for images, graphs, and tables.",
                "jeea.cls LaTeX style file available.",
                "Data/replication: data systematically checked by JEEA Data Editor. Authors must provide data, code, and computation details. JEEA endorses DCAS.",
                "Sources of financial support must be stated in every submitted article. Failure to disclose may result in reversal of acceptance.",
                "Submission fee: EUR 100. Waived if all authors in low/middle-income countries. Non-refundable.",
                "Turnaround target: 8 weeks. Accepts transfers from other leading journals.",
            ],
        },
    },
    # ── Political Science ─────────────────────────────────────
    {
        "id": "apsr",
        "name": "American Political Science Review",
        "abbreviation": "APSR",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/american-political-science-review/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "American Political Science Review",
            "word_limit": 11000,
            "word_count_includes": ["body", "abstract"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text or with placeholder; appendix figures lettered (A.1, A.2)",
            },
            "reference_format": "APSA style (author-date; no comma between author and year)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; Word (.docx), LaTeX (Overleaf template available), or PDF accepted.",
                "Most articles under 11,000 words; research notes under 7,000 words. Word count excludes appendices and references but includes abstract text within tables/figures.",
                "Word count must appear on the front page.",
                "3-5 keywords required.",
                "Double-space main text; footnotes and references need not be double-spaced.",
                "Page numbers required on all pages.",
                "Separate title page with title, abstract, keywords, and word count.",
                "Use footnotes, not endnotes (use word processor footnote function). Do not append notes to titles/headings.",
                "Table/figure notes numbered separately, placed below the table/figure.",
                "Up to 4 in-text citations of own published work per author permitted (do not redact self-citations).",
                "Figures/tables: place in text or use placeholder '[Figure/Table 1 about here]'. Must be readable in grayscale; if color, vary by intensity/tones, not just shade.",
                "Full regression tables must be included in an appendix (only key results summarized in text).",
                "Appendix figures/tables lettered (Table A.1, A.2, Figure A.1). Each appendix gets a descriptive title; restart page count.",
                "Online appendices excluded from word count.",
                "Replication materials required upon acceptance; quantitative data and code deposited in APSR Dataverse.",
                "Pre-analysis plans encouraged (expected for experiments); should be anonymized in online appendix.",
                "ORCID required for corresponding authors.",
                "Cover letter should confirm word count and exclusive submission.",
                "Conflict of interest disclosure required.",
                "Ethics statement required for human subjects research.",
                "Funding sources must be disclosed.",
                "Article types: Research Article, Research Note, Registered Report, Synthesis, Replication/Reappraisal.",
            ],
        },
    },
    {
        "id": "ajps",
        "name": "American Journal of Political Science",
        "abbreviation": "AJPS",
        "field": "political_science",
        "guidelines_url": "https://ajps.org/guidelines-for-manuscripts/",
        "rules": {
            "journal_name": "American Journal of Political Science",
            "word_limit": 10000,
            "word_count_includes": ["body"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document; figures/tables may be single-spaced",
            },
            "reference_format": "APSA Style Manual (revised 2018, updated 2023) or Chicago Manual of Style 18th ed. (author-date). Full first and last names in references.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; PDF, Word, or LaTeX accepted as single anonymous file.",
                "10,000-word maximum — manuscripts exceeding this will not be reviewed.",
                "Abstract should cover background, hypotheses, methods, findings, conclusions. Generally no references in abstract.",
                "Separate title page with title, abstract, and word count only.",
                "Do not number or letter section headings.",
                "Remove all author-identifying info: names, affiliations, acknowledgments, presentation history.",
                "Figures must be black and white or grayscale (color available online only).",
                "Online Supporting Information (SI) is mandatory for quantitative papers: must include full regression tables, robustness checks, and additional analyses. Max 25 pages for original submissions.",
                "SI is reviewed alongside the manuscript.",
                "Mandatory Verification Policy: replication materials verified by third party BEFORE final acceptance.",
                "All data and code must be deposited in the AJPS Dataverse (Harvard Dataverse Network).",
                "Experimental papers must include pre-registration information.",
                "AJPS does NOT accept papers previously rejected by AJPS.",
                "'Research Note' format (new 2025): max 4,000 words, limited to methodology papers and meta-analyses.",
            ],
        },
    },
    {
        "id": "jop",
        "name": "Journal of Politics",
        "abbreviation": "JOP",
        "field": "political_science",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jop/instruct",
        "rules": {
            "journal_name": "Journal of Politics",
            "word_limit": None,
            "page_limit": 35,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document; tables/figures should not exceed a single page if possible",
            },
            "reference_format": "Chicago Manual of Style (author-date). Full author names in references (not initials only).",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; PDF preferred, Word accepted.",
                "Research articles: max 35 pages including all text, footnotes, references, tables/figures.",
                "Short articles: max 10 pages double-spaced; must stand on their own without supplemental files.",
                "Online appendices: max 25 pages for both article types.",
                "Serif typeface for body (e.g., Times Roman); sans serif (e.g., Arial) for titles/headings.",
                "10- or 11-point font permitted but page length may need adjustment.",
                "New paragraphs indicated by indenting first line; no extra space between paragraphs.",
                "Separate title page with title, abstract, keywords, and word/page count.",
                "Footnotes numbered consecutively; substantive notes only.",
                "No separate summary statistics table unless values are explicitly relevant to analysis; summary statistics encouraged in online appendix.",
                "Label appendices with capital letters only (Appendix A, Appendix B), not numbers or mixed.",
                "Replication data and code required upon acceptance; deposited with JOP Dataverse, including specialized software/syntax files.",
                "Human subjects research: include statement of compliance and IRB approval/exemption.",
            ],
        },
    },
    {
        "id": "bjps",
        "name": "British Journal of Political Science",
        "abbreviation": "BJPS",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/british-journal-of-political-science/information/author-instructions",
        "rules": {
            "journal_name": "British Journal of Political Science",
            "word_limit": 10000,
            "word_count_includes": ["body"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Harvard",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text close to where discussed (not on separate sheets); tables max 190x120mm",
            },
            "reference_format": "Harvard style (author-date). No issue numbers in journal references (unless online-only). Full reference list at end.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne; Word (.docx) preferred, PDF accepted. LaTeX style file/Overleaf template available.",
                "Research articles: 4,000-10,000 words. Over 10,000 considered only in exceptional circumstances.",
                "'Letter' format available (up to 4,000 words).",
                "5-7 keywords required.",
                "British spelling required throughout.",
                "Double-space everything including footnotes and references.",
                "Separate title page with title, abstract, keywords, and word count.",
                "Footnotes numbered consecutively (not endnotes); keep to a minimum.",
                "Tables and figures placed IN text close to where discussed (not on separate sheets). Tables designed to fit 190x120mm.",
                "Tables: no vertical lines between columns. Horizontal lines only at top, bottom, and below column headings.",
                "Up to six additional sections before references (except Appendices, which go after references).",
                "Online appendix required for quantitative empirical papers: must contain full regression output, robustness checks, and sensitivity analyses.",
                "Online appendix is peer-reviewed alongside main text.",
                "DA-RT signatory. Replication package required upon acceptance; data, code, and documentation deposited at BJPolS Dataverse (Harvard Dataverse).",
                "ORCID required for corresponding authors.",
                "Data Availability Statement encouraged.",
                "Cover letter should confirm exclusivity and word count.",
                "Conflict of interest disclosure required.",
                "Ethical approval documentation required for human subjects research.",
                "May retain third-person self-citations for anonymization.",
            ],
        },
    },
    {
        "id": "cps",
        "name": "Comparative Political Studies",
        "abbreviation": "CPS",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/cps",
        "rules": {
            "journal_name": "Comparative Political Studies",
            "word_limit": 12000,
            "word_count_includes": ["body", "abstract", "footnotes", "references"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APA",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text at appropriate location (not at end); do not use placeholders",
            },
            "reference_format": "APA reference style",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (mc.manuscriptcentral.com/comppolstud); Word (.doc) or LaTeX submitted as PDF.",
                "12,000-word maximum including abstract, notes, references, tables, and figures. Longer submissions not considered.",
                "Minimum 2 keywords after abstract (as specific as possible).",
                "Partial triple-blind review: editors learn identity (administrative); external reviewers do not.",
                "Remove all author names, affiliations, acknowledgments, funding, conference presentations. File must be named 'blinded version'.",
                "Tables and figures placed at appropriate location within text (not at end). Do not use 'Table 1 Here' placeholders.",
                "Uses endnotes, NOT footnotes — numbered consecutively, placed before references.",
                "Quantitative papers require data, code, and log files deposited at CPS Dataverse (Harvard) before final acceptance.",
                "Must be willing to provide datasets upon request.",
                "Must provide names of potential reviewers during submission.",
                "Cover letter should describe the paper's contribution and confirm exclusive submission.",
            ],
        },
    },
    {
        "id": "world-politics",
        "name": "World Politics",
        "abbreviation": "WP",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/world-politics/information/instructions-contributors",
        "rules": {
            "journal_name": "World Politics",
            "word_limit": 12500,
            "word_count_includes": ["body", "footnotes"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on its own page",
            },
            "reference_format": "Chicago Manual of Style (author-date). Footnotes (numbered) with reference list.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (mc.manuscriptcentral.com/wp); Word or PDF accepted.",
                "Research and review articles: up to 12,500 words including notes. Tables, figures, and appendixes excluded from word count.",
                "Supplementary material: max 15 pages (not copyedited; posted as submitted).",
                "Triple-blind review: authors anonymous to reviewers AND editorial committee members.",
                "Remove bylines, identifying info, and self-cites if possible.",
                "Uses footnotes (numbered consecutively) with a reference list. Do not use two or more note numbers following a sentence (combine into one).",
                "Acknowledgments at end of manuscript after reference list (not as a numbered note).",
                "Online appendix for supplementary material; statistical appendices with full results encouraged.",
                "If AI tools used for translating, proofreading, or formatting, must disclose which tool and how used.",
                "No opinion pieces, policy pieces, political theory articles, historical articles, or journalistic narratives.",
                "Published by Johns Hopkins University Press.",
            ],
        },
    },
    {
        "id": "io",
        "name": "International Organization",
        "abbreviation": "IO",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/international-organization/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "International Organization",
            "word_limit": 14000,
            "word_count_includes": ["body", "footnotes"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "included as part of main manuscript",
            },
            "reference_format": "IO house style: short author-date footnotes (not parenthetical in-text). Chicago Manual of Style 16th ed. Reference list with complete publication facts.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager (io.edmgr.com); Word (.docx) or PDF accepted. Overleaf template available.",
                "Research articles: max 14,000 words. Research notes: max 8,000 words.",
                "Abstract, word count, and acknowledgments submitted separately from manuscript.",
                "Self-references after title page should be omitted if they reveal identity. Refer to own work in third person; use 'they' not 'I/we'.",
                "Uses short author-date footnotes for citation (not parenthetical in-text references) in accepted papers. At submission, any standard citation format is fine.",
                "Figures and tables included as part of main manuscript.",
                "Tables: only horizontal rules (three-line table format). Each table/figure must include a descriptive title and source notes.",
                "Online appendix strongly encouraged: full regression output, robustness tests, and additional analyses. Appendix is reviewed as part of the submission.",
                "ORCID required for corresponding authors.",
                "IO Data Access & Research Transparency (DA-RT) policy.",
                "Replication data and code must be deposited at IO Dataverse upon acceptance.",
                "Pre-registration encouraged for experiments.",
                "Authors asked to be mindful of gender, race, ethnicity, and geographic biases in citations.",
                "Research ethics disclosure required for experimental/survey work.",
                "Conflict of interest statement required.",
                "Will not consider manuscripts with half or more ideas/evidence published or under review elsewhere.",
                "Will not consider revised versions of previously submitted IO manuscripts.",
                "Acceptance rate approximately 5%.",
            ],
        },
    },
    {
        "id": "political-analysis",
        "name": "Political Analysis",
        "abbreviation": "PA",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/political-analysis/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "Political Analysis",
            "word_limit": 6000,
            "word_count_includes": ["body"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 200,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "embedded in text during review; separate files upon conditional acceptance. Figure text/labels: use Verdana or Arial.",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": False,
            "additional_notes": [
                "Submit via ScholarOne (mc.manuscriptcentral.com/pa); Word or LaTeX accepted (LaTeX must also provide PDF). Overleaf template available.",
                "Research articles: up to 6,000 words excluding references. Letters: up to 2,500 words excluding references.",
                "Longer manuscripts considered at initial submission but must meet limits upon revision.",
                "3-5 keywords required.",
                "Single-blind review (authors do NOT need to anonymize). Anonymized manuscripts will be returned.",
                "ORCID required for corresponding authors.",
                "Double-spaced, 12-point font, page numbers included. No line numbers (added by submission system).",
                "Footnotes at bottom of page (not endnotes).",
                "Figures and tables embedded in text during review. Upon conditional acceptance, submit as separate files.",
                "Figure text/labels: use Verdana or Arial fonts.",
                "Code for reproducing all figures must be included in replication materials.",
                "Mandatory replication policy: ALL data and code must be publicly available before publication. Notify editor at submission if data access is restricted.",
                "Verification of replication materials before publication.",
                "Software dependencies must be documented.",
            ],
        },
    },
    {
        "id": "arps",
        "name": "Annual Review of Political Science",
        "abbreviation": "ARPS",
        "field": "political_science",
        "guidelines_url": "https://www.annualreviews.org/page/authors/general-information",
        "rules": {
            "journal_name": "Annual Review of Political Science",
            "word_limit": 15000,
            "word_count_includes": ["body", "references"],
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [
                "Abstract",
                "Introduction",
                "Summary Points",
                "Future Issues",
            ],
            "abstract_word_limit": 150,
            "citation_style": "Numbered",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "each figure as a separate file; do not embed in text. Also provide single PDF with all figures. SVG acceptable if PDF unavailable.",
            },
            "reference_format": "Annual Reviews citation style (check with Production Editor for ARPS-specific format)",
            "anonymization_required": False,
            "additional_notes": [
                "Invited review articles only — authors are commissioned by the editorial committee.",
                "Word (.docx) or TeX accepted (include .bib and associated files for TeX).",
                "Article length as specified in invitation letter.",
                "150-word abstract maximum.",
                "Up to 6 keywords (should not duplicate words already in the title).",
                "Do not use less than 12-point or space-and-a-half.",
                "Page order: title page, text, literature cited, article components, figure captions, tables, figures.",
                "Title page: full article title, author name(s) and affiliation(s) with email(s), corresponding author designation.",
                "Summary Points: up to 8 complete sentences.",
                "Future Issues: up to 8 key questions for future research.",
                "Optional sections: Reference Annotations (15 words max each), Related Resources (up to 10), Sidebar (50-200 words), Terms and Definitions (up to 20 terms, 20 words max each).",
                "Tables placed at end of article after Literature Cited, or in a separate file.",
                "Footnotes not typically used — all information should be in main text.",
                "Color figures encouraged; Annual Reviews provides professional figure editing.",
                "Supplemental material: submit concurrently; must be called out in text (e.g., 'see Supplemental Figure 1').",
                "Annual Reviews does not seek copyright.",
                "Professional copyediting and typesetting provided.",
            ],
        },
    },
    {
        "id": "jcr",
        "name": "Journal of Conflict Resolution",
        "abbreviation": "JCR",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/jcr",
        "rules": {
            "journal_name": "Journal of Conflict Resolution",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "on separate pages; color free online, fees for color in print",
            },
            "reference_format": "Chicago Manual of Style",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via SAGE Track; Word preferred, LaTeX accepted (SAGE template available).",
                "Word count must appear on title page.",
                "Minimum 4 keywords, listed after abstract.",
                "Double-spaced throughout. Footnotes, references, tables, and graphs on separate pages.",
                "Author name and affiliation on separate cover page only; all other documents fully anonymized.",
                "Figures: 300 dpi. Color free in online version; fees for color in print.",
                "Supplementary material: max 20 pages. Journal can host additional materials online (datasets, podcasts, videos, images).",
                "All tables and figures must be referenced in text.",
                "Full regression tables and robustness checks in appendix.",
                "Strict replication policy: all data, specialized programs, recodes, and explanatory file required. Files sent to Managing Editor. Must be posted by month of publication.",
                "Conflict of interest declaration required from all authors.",
                "Funding statement required under separate heading (even if no funding received).",
                "'Research Note' format available for shorter contributions.",
            ],
        },
    },
]


def get_presets_list() -> list[dict]:
    """Return a lightweight list of presets for the frontend dropdown."""
    return [
        {
            "id": p["id"],
            "name": p["name"],
            "guidelines_url": p.get("guidelines_url"),
            "abbreviation": p["abbreviation"],
            "field": p["field"],
        }
        for p in JOURNAL_PRESETS
    ]


def get_preset_rules(preset_id: str) -> dict | None:
    """Return the full rules dict for a given preset ID."""
    for p in JOURNAL_PRESETS:
        if p["id"] == preset_id:
            return p["rules"]
    return None
