"""Pre-populated submission guidelines for top journals in economics and political science."""

JOURNAL_PRESETS: list[dict] = [
    # ── Economics ──────────────────────────────────────────────
    {
        "id": "aer",
        "name": "American Economic Review",
        "abbreviation": "AER",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/aer/submissions",
        "rules": {
            "journal_name": "American Economic Review",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required (up to 5).",
                "Up to 5 keywords required.",
                "Submit as PDF only for initial submission.",
                "Separate title page with title, abstract, JEL codes, and keywords (no author info).",
                "Footnotes numbered consecutively (not endnotes).",
                "Figures and tables at end of manuscript, each on a separate page.",
                "Online appendices accepted for supplementary material.",
                "AEA Data and Code Availability Policy applies upon acceptance; replication packages required.",
                "LaTeX submissions should use the AEA template.",
                "Self-citations must be in third person for anonymity.",
                "Submission fee: $350 for non-AEA members; free for AEA members.",
                "Previously rejected papers may not be resubmitted.",
            ],
        },
    },
    {
        "id": "econometrica",
        "name": "Econometrica",
        "abbreviation": "ECMA",
        "field": "economics",
        "guidelines_url": "https://www.econometricsociety.org/publications/econometrica/information-authors",
        "rules": {
            "journal_name": "Econometrica",
            "word_limit": None,
            "page_limit": 45,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "Econometrica house style (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express as PDF.",
                "45-page limit includes all content; papers exceeding this may be desk-rejected.",
                "Title page: title and abstract only (no identifying information).",
                "Footnotes numbered consecutively (not endnotes).",
                "Supplementary material in a separate online supplement (proofs, data appendices).",
                "Replication package required upon acceptance; code and data deposited with the journal.",
                "Econometrica LaTeX style file available and recommended.",
                "Mathematical notation should follow Econometrica conventions.",
                "Theorems, lemmas, and propositions must be numbered consecutively.",
            ],
        },
    },
    {
        "id": "qje",
        "name": "Quarterly Journal of Economics",
        "abbreviation": "QJE",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/qje/pages/Instructions_To_Authors",
        "rules": {
            "journal_name": "Quarterly Journal of Economics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page with descriptive title",
            },
            "reference_format": "Author-date (Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (OUP); PDF or Word accepted.",
                "Triple-blind review process.",
                "Separate title page with title and abstract only.",
                "Footnotes numbered consecutively (not endnotes).",
                "Figures and tables at end, each on a separate page with descriptive titles.",
                "Online appendix accepted for additional results, proofs, and robustness checks.",
                "Data and code availability policy: replication package required upon acceptance, deposited in QJE Dataverse.",
                "No submission fee.",
            ],
        },
    },
    {
        "id": "jpe",
        "name": "Journal of Political Economy",
        "abbreviation": "JPE",
        "field": "economics",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jpe/instruct",
        "rules": {
            "journal_name": "Journal of Political Economy",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "Chicago Manual of Style 17th ed. (author-date)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts as PDF.",
                "Separate title page with title and abstract; no author identification in manuscript.",
                "JEL classification codes requested.",
                "Footnotes numbered consecutively (not endnotes).",
                "Tables should be formatted using tabs (not spaces or graphic elements).",
                "All figures must have descriptive captions.",
                "Mathematical appendices may be placed in online supplement.",
                "Mandatory data/code availability upon acceptance; deposited at journal's data repository.",
                "Self-citations should be in third person for anonymity.",
                "Submission fee: $250.",
            ],
        },
    },
    {
        "id": "restud",
        "name": "Review of Economic Studies",
        "abbreviation": "ReStud",
        "field": "economics",
        "guidelines_url": "https://www.restud.com/submissions/",
        "rules": {
            "journal_name": "Review of Economic Studies",
            "word_limit": None,
            "page_limit": 50,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a new page",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Express as PDF.",
                "Manuscript should not exceed approximately 50 pages including appendices.",
                "Title page: title and abstract only (no author info).",
                "JEL classification codes required.",
                "Footnotes numbered consecutively (not endnotes).",
                "Online appendix for supplementary proofs, tables, and robustness checks.",
                "Papers should be self-contained (main results in body, not just appendix).",
                "Data and code replication materials required upon acceptance.",
                "ReStud uses a 'reject and resubmit' model (no revise and resubmit).",
            ],
        },
    },
    {
        "id": "aej-applied",
        "name": "AEJ: Applied Economics",
        "abbreviation": "AEJ:Applied",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/app/submissions",
        "rules": {
            "journal_name": "American Economic Journal: Applied Economics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required (up to 5).",
                "Up to 5 keywords required.",
                "Submit as PDF only via AEA submission portal.",
                "Separate title page with title, abstract, JEL codes, and keywords.",
                "Footnotes numbered consecutively (not endnotes).",
                "Online appendix accepted for supplementary material.",
                "AEA Data and Code Availability Policy applies.",
                "Submission fee: $350 for non-AEA members; free for AEA members.",
                "Shorter papers welcome.",
            ],
        },
    },
    {
        "id": "aej-macro",
        "name": "AEJ: Macroeconomics",
        "abbreviation": "AEJ:Macro",
        "field": "economics",
        "guidelines_url": "https://www.aeaweb.org/journals/mac/submissions",
        "rules": {
            "journal_name": "American Economic Journal: Macroeconomics",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "1.5",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "AEA style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "JEL classification codes required (up to 5).",
                "Up to 5 keywords required.",
                "Submit as PDF only via AEA submission portal.",
                "Separate title page with title, abstract, JEL codes, and keywords.",
                "Footnotes numbered consecutively (not endnotes).",
                "Online appendix accepted for supplementary material.",
                "AEA Data and Code Availability Policy applies.",
                "Submission fee: $350 for non-AEA members; free for AEA members.",
            ],
        },
    },
    {
        "id": "jof",
        "name": "Journal of Finance",
        "abbreviation": "JF",
        "field": "economics",
        "guidelines_url": "https://afajof.org/submissions/",
        "rules": {
            "journal_name": "Journal of Finance",
            "word_limit": None,
            "page_limit": 60,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "Journal of Finance house style (author-date, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne/Manuscript Central; PDF or Word accepted.",
                "60-page limit includes all content.",
                "Separate title page with title and abstract; no author information in body.",
                "Tables should be self-contained with descriptive titles and notes.",
                "Footnotes numbered consecutively (not endnotes).",
                "Internet Appendix accepted for additional tables, figures, and proofs.",
                "JEL classification codes recommended.",
                "Disclosure statement required regarding funding and conflicts of interest.",
                "Code and data sharing required upon acceptance.",
                "Self-referencing should be in third person.",
                "Submission fee: $500 for non-AFA members; $250 for AFA members.",
            ],
        },
    },
    {
        "id": "restat",
        "name": "Review of Economics and Statistics",
        "abbreviation": "ReStat",
        "field": "economics",
        "guidelines_url": "https://direct.mit.edu/rest/pages/submission-guidelines",
        "rules": {
            "journal_name": "Review of Economics and Statistics",
            "word_limit": None,
            "page_limit": 40,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 100,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "Author-date (house style, Chicago-based)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (MIT Press); PDF or Word accepted.",
                "Approximately 40 pages including tables, figures, and references; shorter papers strongly preferred.",
                "Title page: title and abstract only (no author information).",
                "JEL classification codes required.",
                "Footnotes numbered consecutively.",
                "Online appendix accepted for supplementary material.",
                "Mandatory data and code availability policy; replication package required.",
                "Submission fee: $300 for non-subscribers.",
            ],
        },
    },
    {
        "id": "jeea",
        "name": "Journal of the European Economic Association",
        "abbreviation": "JEEA",
        "field": "economics",
        "guidelines_url": "https://academic.oup.com/jeea/pages/Author_Guidelines",
        "rules": {
            "journal_name": "Journal of the European Economic Association",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on a separate page",
            },
            "reference_format": "Author-date (house style)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (OUP); PDF or Word accepted.",
                "Separate title page with title, abstract, and JEL codes (no author info).",
                "JEL classification codes required.",
                "Up to 5 keywords required.",
                "Footnotes numbered consecutively (not endnotes).",
                "Tables should have descriptive titles and notes; figures should include detailed captions.",
                "Online appendix for additional material.",
                "Data and code sharing policy; replication package upon acceptance.",
                "Submission fee: none for EEA members; fee for non-members.",
            ],
        },
    },
    # ── Political Science ─────────────────────────────────────
    {
        "id": "apsr",
        "name": "American Political Science Review",
        "abbreviation": "APSR",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/american-political-science-review/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "American Political Science Review",
            "word_limit": 11000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text or with placeholder; appendix figures lettered (A.1, A.2)",
            },
            "reference_format": "APSA style (author-date; no comma between author and year)",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; Word (.docx), LaTeX (Overleaf template available), or PDF accepted.",
                "Most articles under 11,000 words; research notes under 7,000 words. Word count excludes appendices and references but includes abstract text within tables/figures.",
                "Word count must appear on the front page.",
                "3-5 keywords required.",
                "Double-space main text; footnotes and references need not be double-spaced.",
                "Page numbers required on all pages.",
                "Separate title page with title, abstract, keywords, and word count.",
                "Use footnotes, not endnotes (use word processor footnote function). Do not append notes to titles/headings.",
                "Table/figure notes numbered separately, placed below the table/figure.",
                "Up to 4 in-text citations of own published work per author permitted (do not redact self-citations).",
                "Figures/tables: place in text or use placeholder '[Figure/Table 1 about here]'. Must be readable in grayscale; if color, vary by intensity/tones, not just shade.",
                "Full regression tables must be included in an appendix (only key results summarized in text).",
                "Appendix figures/tables lettered (Table A.1, A.2, Figure A.1). Each appendix gets a descriptive title; restart page count.",
                "Online appendices excluded from word count.",
                "Replication materials required upon acceptance; quantitative data and code deposited in APSR Dataverse.",
                "Pre-analysis plans encouraged (expected for experiments); should be anonymized in online appendix.",
                "ORCID required for corresponding authors.",
                "Cover letter should confirm word count and exclusive submission.",
                "Conflict of interest disclosure required.",
                "Ethics statement required for human subjects research.",
                "Funding sources must be disclosed.",
                "Article types: Research Article, Research Note, Registered Report, Synthesis, Replication/Reappraisal.",
            ],
        },
    },
    {
        "id": "ajps",
        "name": "American Journal of Political Science",
        "abbreviation": "AJPS",
        "field": "political_science",
        "guidelines_url": "https://ajps.org/guidelines-for-manuscripts/",
        "rules": {
            "journal_name": "American Journal of Political Science",
            "word_limit": 10000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document; figures/tables may be single-spaced",
            },
            "reference_format": "APSA Style Manual (revised 2018, updated 2023) or Chicago Manual of Style 18th ed. (author-date). Full first and last names in references.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; PDF, Word, or LaTeX accepted as single anonymous file.",
                "10,000-word maximum — manuscripts exceeding this will not be reviewed.",
                "Abstract should cover background, hypotheses, methods, findings, conclusions. Generally no references in abstract.",
                "Separate title page with title, abstract, and word count only.",
                "Do not number or letter section headings.",
                "Remove all author-identifying info: names, affiliations, acknowledgments, presentation history.",
                "Figures must be black and white or grayscale (color available online only).",
                "Online Supporting Information (SI) is mandatory for quantitative papers: must include full regression tables, robustness checks, and additional analyses. Max 25 pages for original submissions.",
                "SI is reviewed alongside the manuscript.",
                "Mandatory Verification Policy: replication materials verified by third party BEFORE final acceptance.",
                "All data and code must be deposited in the AJPS Dataverse (Harvard Dataverse Network).",
                "Experimental papers must include pre-registration information.",
                "AJPS does NOT accept papers previously rejected by AJPS.",
                "'Research Note' format (new 2025): max 4,000 words, limited to methodology papers and meta-analyses.",
            ],
        },
    },
    {
        "id": "jop",
        "name": "Journal of Politics",
        "abbreviation": "JOP",
        "field": "political_science",
        "guidelines_url": "https://www.journals.uchicago.edu/journals/jop/instruct",
        "rules": {
            "journal_name": "Journal of Politics",
            "word_limit": None,
            "page_limit": 35,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document; tables/figures should not exceed a single page if possible",
            },
            "reference_format": "Chicago Manual of Style (author-date). Full author names in references (not initials only).",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager; PDF preferred, Word accepted.",
                "Research articles: max 35 pages including all text, footnotes, references, tables/figures.",
                "Short articles: max 10 pages double-spaced; must stand on their own without supplemental files.",
                "Online appendices: max 25 pages for both article types.",
                "Serif typeface for body (e.g., Times Roman); sans serif (e.g., Arial) for titles/headings.",
                "10- or 11-point font permitted but page length may need adjustment.",
                "New paragraphs indicated by indenting first line; no extra space between paragraphs.",
                "Separate title page with title, abstract, keywords, and word/page count.",
                "Footnotes numbered consecutively; substantive notes only.",
                "No separate summary statistics table unless values are explicitly relevant to analysis; summary statistics encouraged in online appendix.",
                "Label appendices with capital letters only (Appendix A, Appendix B), not numbers or mixed.",
                "Replication data and code required upon acceptance; deposited with JOP Dataverse, including specialized software/syntax files.",
                "Human subjects research: include statement of compliance and IRB approval/exemption.",
            ],
        },
    },
    {
        "id": "bjps",
        "name": "British Journal of Political Science",
        "abbreviation": "BJPS",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/british-journal-of-political-science/information/author-instructions",
        "rules": {
            "journal_name": "British Journal of Political Science",
            "word_limit": 10000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Harvard",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text close to where discussed (not on separate sheets); tables max 190x120mm",
            },
            "reference_format": "Harvard style (author-date). No issue numbers in journal references (unless online-only). Full reference list at end.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne; Word (.docx) preferred, PDF accepted. LaTeX style file/Overleaf template available.",
                "Research articles: 4,000-10,000 words. Over 10,000 considered only in exceptional circumstances.",
                "'Letter' format available (up to 4,000 words).",
                "5-7 keywords required.",
                "British spelling required throughout.",
                "Double-space everything including footnotes and references.",
                "Separate title page with title, abstract, keywords, and word count.",
                "Footnotes numbered consecutively (not endnotes); keep to a minimum.",
                "Tables and figures placed IN text close to where discussed (not on separate sheets). Tables designed to fit 190x120mm.",
                "Tables: no vertical lines between columns. Horizontal lines only at top, bottom, and below column headings.",
                "Up to six additional sections before references (except Appendices, which go after references).",
                "Online appendix required for quantitative empirical papers: must contain full regression output, robustness checks, and sensitivity analyses.",
                "Online appendix is peer-reviewed alongside main text.",
                "DA-RT signatory. Replication package required upon acceptance; data, code, and documentation deposited at BJPolS Dataverse (Harvard Dataverse).",
                "ORCID required for corresponding authors.",
                "Data Availability Statement encouraged.",
                "Cover letter should confirm exclusivity and word count.",
                "Conflict of interest disclosure required.",
                "Ethical approval documentation required for human subjects research.",
                "May retain third-person self-citations for anonymization.",
            ],
        },
    },
    {
        "id": "cps",
        "name": "Comparative Political Studies",
        "abbreviation": "CPS",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/cps",
        "rules": {
            "journal_name": "Comparative Political Studies",
            "word_limit": 12000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "APA",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "in text at appropriate location (not at end); do not use placeholders",
            },
            "reference_format": "APA reference style",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (mc.manuscriptcentral.com/comppolstud); Word (.doc) or LaTeX submitted as PDF.",
                "12,000-word maximum including abstract, notes, references, tables, and figures. Longer submissions not considered.",
                "Minimum 2 keywords after abstract (as specific as possible).",
                "Partial triple-blind review: editors learn identity (administrative); external reviewers do not.",
                "Remove all author names, affiliations, acknowledgments, funding, conference presentations. File must be named 'blinded version'.",
                "Tables and figures placed at appropriate location within text (not at end). Do not use 'Table 1 Here' placeholders.",
                "Uses endnotes, NOT footnotes — numbered consecutively, placed before references.",
                "Quantitative papers require data, code, and log files deposited at CPS Dataverse (Harvard) before final acceptance.",
                "Must be willing to provide datasets upon request.",
                "Must provide names of potential reviewers during submission.",
                "Cover letter should describe the paper's contribution and confirm exclusive submission.",
            ],
        },
    },
    {
        "id": "world-politics",
        "name": "World Politics",
        "abbreviation": "WP",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/world-politics/information/instructions-contributors",
        "rules": {
            "journal_name": "World Politics",
            "word_limit": 12500,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "end of document, each on its own page",
            },
            "reference_format": "Chicago Manual of Style (author-date). Footnotes (numbered) with reference list.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via ScholarOne Manuscripts (mc.manuscriptcentral.com/wp); Word or PDF accepted.",
                "Research and review articles: up to 12,500 words including notes. Tables, figures, and appendixes excluded from word count.",
                "Supplementary material: max 15 pages (not copyedited; posted as submitted).",
                "Triple-blind review: authors anonymous to reviewers AND editorial committee members.",
                "Remove bylines, identifying info, and self-cites if possible.",
                "Uses footnotes (numbered consecutively) with a reference list. Do not use two or more note numbers following a sentence (combine into one).",
                "Acknowledgments at end of manuscript after reference list (not as a numbered note).",
                "Online appendix for supplementary material; statistical appendices with full results encouraged.",
                "If AI tools used for translating, proofreading, or formatting, must disclose which tool and how used.",
                "No opinion pieces, policy pieces, political theory articles, historical articles, or journalistic narratives.",
                "Published by Johns Hopkins University Press.",
            ],
        },
    },
    {
        "id": "io",
        "name": "International Organization",
        "abbreviation": "IO",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/international-organization/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "International Organization",
            "word_limit": 14000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "included as part of main manuscript",
            },
            "reference_format": "IO house style: short author-date footnotes (not parenthetical in-text). Chicago Manual of Style 16th ed. Reference list with complete publication facts.",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via Editorial Manager (io.edmgr.com); Word (.docx) or PDF accepted. Overleaf template available.",
                "Research articles: max 14,000 words. Research notes: max 8,000 words.",
                "Abstract, word count, and acknowledgments submitted separately from manuscript.",
                "Self-references after title page should be omitted if they reveal identity. Refer to own work in third person; use 'they' not 'I/we'.",
                "Uses short author-date footnotes for citation (not parenthetical in-text references) in accepted papers. At submission, any standard citation format is fine.",
                "Figures and tables included as part of main manuscript.",
                "Tables: only horizontal rules (three-line table format). Each table/figure must include a descriptive title and source notes.",
                "Online appendix strongly encouraged: full regression output, robustness tests, and additional analyses. Appendix is reviewed as part of the submission.",
                "ORCID required for corresponding authors.",
                "IO Data Access & Research Transparency (DA-RT) policy.",
                "Replication data and code must be deposited at IO Dataverse upon acceptance.",
                "Pre-registration encouraged for experiments.",
                "Authors asked to be mindful of gender, race, ethnicity, and geographic biases in citations.",
                "Research ethics disclosure required for experimental/survey work.",
                "Conflict of interest statement required.",
                "Will not consider manuscripts with half or more ideas/evidence published or under review elsewhere.",
                "Will not consider revised versions of previously submitted IO manuscripts.",
                "Acceptance rate approximately 5%.",
            ],
        },
    },
    {
        "id": "political-analysis",
        "name": "Political Analysis",
        "abbreviation": "PA",
        "field": "political_science",
        "guidelines_url": "https://www.cambridge.org/core/journals/political-analysis/information/author-instructions/preparing-your-materials",
        "rules": {
            "journal_name": "Political Analysis",
            "word_limit": 6000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 200,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "embedded in text during review; separate files upon conditional acceptance. Figure text/labels: use Verdana or Arial.",
            },
            "reference_format": "APSA style (author-date)",
            "anonymization_required": False,
            "additional_notes": [
                "Submit via ScholarOne (mc.manuscriptcentral.com/pa); Word or LaTeX accepted (LaTeX must also provide PDF). Overleaf template available.",
                "Research articles: up to 6,000 words excluding references. Letters: up to 2,500 words excluding references.",
                "Longer manuscripts considered at initial submission but must meet limits upon revision.",
                "3-5 keywords required.",
                "Single-blind review (authors do NOT need to anonymize). Anonymized manuscripts will be returned.",
                "ORCID required for corresponding authors.",
                "Double-spaced, 12-point font, page numbers included. No line numbers (added by submission system).",
                "Footnotes at bottom of page (not endnotes).",
                "Figures and tables embedded in text during review. Upon conditional acceptance, submit as separate files.",
                "Figure text/labels: use Verdana or Arial fonts.",
                "Code for reproducing all figures must be included in replication materials.",
                "Mandatory replication policy: ALL data and code must be publicly available before publication. Notify editor at submission if data access is restricted.",
                "Verification of replication materials before publication.",
                "Software dependencies must be documented.",
            ],
        },
    },
    {
        "id": "arps",
        "name": "Annual Review of Political Science",
        "abbreviation": "ARPS",
        "field": "political_science",
        "guidelines_url": "https://www.annualreviews.org/page/authors/general-information",
        "rules": {
            "journal_name": "Annual Review of Political Science",
            "word_limit": 15000,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [
                "Abstract",
                "Introduction",
                "Summary Points",
                "Future Issues",
            ],
            "abstract_word_limit": 150,
            "citation_style": "Numbered",
            "figure_requirements": {
                "formats": ["PDF", "EPS", "TIFF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "each figure as a separate file; do not embed in text. Also provide single PDF with all figures. SVG acceptable if PDF unavailable.",
            },
            "reference_format": "Annual Reviews citation style (check with Production Editor for ARPS-specific format)",
            "anonymization_required": False,
            "additional_notes": [
                "Invited review articles only — authors are commissioned by the editorial committee.",
                "Word (.docx) or TeX accepted (include .bib and associated files for TeX).",
                "Article length as specified in invitation letter.",
                "150-word abstract maximum.",
                "Up to 6 keywords (should not duplicate words already in the title).",
                "Do not use less than 12-point or space-and-a-half.",
                "Page order: title page, text, literature cited, article components, figure captions, tables, figures.",
                "Title page: full article title, author name(s) and affiliation(s) with email(s), corresponding author designation.",
                "Summary Points: up to 8 complete sentences.",
                "Future Issues: up to 8 key questions for future research.",
                "Optional sections: Reference Annotations (15 words max each), Related Resources (up to 10), Sidebar (50-200 words), Terms and Definitions (up to 20 terms, 20 words max each).",
                "Tables placed at end of article after Literature Cited, or in a separate file.",
                "Footnotes not typically used — all information should be in main text.",
                "Color figures encouraged; Annual Reviews provides professional figure editing.",
                "Supplemental material: submit concurrently; must be called out in text (e.g., 'see Supplemental Figure 1').",
                "Annual Reviews does not seek copyright.",
                "Professional copyediting and typesetting provided.",
            ],
        },
    },
    {
        "id": "jcr",
        "name": "Journal of Conflict Resolution",
        "abbreviation": "JCR",
        "field": "political_science",
        "guidelines_url": "https://journals.sagepub.com/author-instructions/jcr",
        "rules": {
            "journal_name": "Journal of Conflict Resolution",
            "word_limit": None,
            "page_limit": None,
            "font": "Times New Roman",
            "font_size": 12.0,
            "line_spacing": "double",
            "margins": "1 inch all sides",
            "required_sections": [],
            "abstract_word_limit": 150,
            "citation_style": "Chicago",
            "figure_requirements": {
                "formats": ["TIFF", "EPS", "PDF"],
                "min_resolution_dpi": 300,
                "max_file_size_mb": None,
                "placement": "on separate pages; color free online, fees for color in print",
            },
            "reference_format": "Chicago Manual of Style",
            "anonymization_required": True,
            "additional_notes": [
                "Submit via SAGE Track; Word preferred, LaTeX accepted (SAGE template available).",
                "Word count must appear on title page.",
                "Minimum 4 keywords, listed after abstract.",
                "Double-spaced throughout. Footnotes, references, tables, and graphs on separate pages.",
                "Author name and affiliation on separate cover page only; all other documents fully anonymized.",
                "Figures: 300 dpi. Color free in online version; fees for color in print.",
                "Supplementary material: max 20 pages. Journal can host additional materials online (datasets, podcasts, videos, images).",
                "All tables and figures must be referenced in text.",
                "Full regression tables and robustness checks in appendix.",
                "Strict replication policy: all data, specialized programs, recodes, and explanatory file required. Files sent to Managing Editor. Must be posted by month of publication.",
                "Conflict of interest declaration required from all authors.",
                "Funding statement required under separate heading (even if no funding received).",
                "'Research Note' format available for shorter contributions.",
            ],
        },
    },
]


def get_presets_list() -> list[dict]:
    """Return a lightweight list of presets for the frontend dropdown."""
    return [
        {
            "id": p["id"],
            "name": p["name"],
            "abbreviation": p["abbreviation"],
            "field": p["field"],
        }
        for p in JOURNAL_PRESETS
    ]


def get_preset_rules(preset_id: str) -> dict | None:
    """Return the full rules dict for a given preset ID."""
    for p in JOURNAL_PRESETS:
        if p["id"] == preset_id:
            return p["rules"]
    return None
